# TODO
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fink-broker
  namespace: argocd
  labels:
    app.kubernetes.io/name: fink-broker
    app.kubernetes.io/part-of: fink-core
spec:
  project: default
  source:
    path: chart/
    repoURL: https://github.com/astrolabsoftware/fink-broker.git
    # TODO use fink-broker hash
    targetRevision: "{{ .Values.finkbroker.revision }}"
    helm:
      releaseName: fink-broker
      valueFiles:
        - "{{ .Values.finkbroker.valueFile }}"
      valuesObject:
        s3:
          bucket: "{{ .Values.s3.bucket }}"
          endpoint: "{{.Values.s3.endpoint }}"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: spark
