apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fink-broker
  namespace: argocd
  labels:
    app.kubernetes.io/name: fink-broker
    app.kubernetes.io/part-of: fink-core
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: chart/
    repoURL: https://github.com/astrolabsoftware/fink-broker.git
    # TODO use fink-broker hash
    targetRevision: "{{ .Values.spec.source.targetRevision.finkbroker }}"
    helm:
      releaseName: fink-broker
      valuesObject:
        {{- if .Values.s3.enabled }}
        storage: s3
        s3:
          bucket: "{{ .Values.s3.bucket }}"
          endpoint: "{{.Values.s3.endpoint }}"
        {{- else if .Values.hdfs.enabled }}
        storage: hdfs
        {{- end }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.sparkNamespace }}
  syncPolicy:
    syncOptions:
    # - Replace=true
    - CreateNamespace=true
