# Requireb by sparkJobNamespaces
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.spec.sparkNamespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
---
# Required by service account spark-operator
# TODO upgrade spark-operator to 2.0.0 and remove RBAC below
apiVersion: v1
kind: Namespace
metadata:
  name: spark-operator
  annotations:
    argocd.argoproj.io/hook: PreSync
