apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/part-of: fink-operator
spec:
  project: default
  source:
    chart: spark-operator
    repoURL: https://kubeflow.github.io/spark-operator
    targetRevision: 1.4.2
    helm:
      releaseName: spark-operator
      valuesObject:
        webhook:
          enable: true
        sparkJobNamespaces: {{ .Values.spec.sparkJobNamespaces }}
        # FIXME: Creating rbac and sa in argocd prevent correct startup of spark-operator
        # see: https://github.com/kubeflow/spark-operator/issues/1894
        serviceAccounts:
          spark:
            create: false
            name: spark
          sparkoperator:
            create: false
            name: spark-operator
        rbac:
          createClusterRole: false
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: spark-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
