apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: strimzi
    app.kubernetes.io/part-of: fink-operator
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kafka
  project: default
  source:
    path: strimzi
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
