{{ if .Values.e2e.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi
  namespace: argocd
  labels:
    app.kubernetes.io/name: strimzi
    app.kubernetes.io/part-of: fink
    app.kubernetes.io/component: operator
spec:
  project: default
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jqPathExpressions:
    - .spec.versions[].deprecated | select(. == false)
  source:
    chart: strimzi-kafka-operator
    repoURL: quay.io/strimzi-helm
    targetRevision: 0.48.0
    helm:
      releaseName: strimzi
      values: |
        resources:
          limits:
            memory: 2Gi
            cpu: 1000m
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kafka
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
{{ end }}
