finkBroker:
  raw2science:
    driver:
      cores: "2"
      memory: "3000m"
    executor:
      cores: "2"
      coreRequest: "0"
      memory: "3000m"
      instances: "2"
  distribution:
    memory: "2000m"
