s3:
  bucket: fink-broker-online
  endpoint: https://minio.minio:443
finkbroker:
  # Revision for the fink-broker chart
  revision: nil
  # value file, must be in fink-broker chart/
  valueFile: nil
spec:
  destination:
    server: https://kubernetes.default.svc
  sparkJobNamespaces: ["spark"]
  source:
    repoURL: https://github.com/astrolabsoftware/fink-cd
    targetRevision: main
