finkBroker:
  night: "20200101"
  logLevel: "DEBUG"
  e2e:
    enabled: true
  monitoring:
    enabled: false
  image:
    repository: ""
    tag: ""
    name: "fink-broker"
  stream2raw:
    kafkaInSockets: ""
    finkAlertSchema: ""
    topic: 'ztf_public_{{.Values.finkBroker.night}}'
  raw2science:
    cores: ""
    coreRequest: ""
    memory: ""
    instances: ""
  distribution:
    memory: ""
finkAlertSimulator:
  image:
    tag: ""
storage: "hdfs"
s3:
  bucket: fink-broker-online
  endpoint: https://minio.minio:443
kafka:
  storageSize: "1Gi"
hdfs:
  storageCapacity: ""
  onlineDataPrefix: "hdfs://simple-hdfs-namenode-default-0.simple-hdfs-namenode-default.hdfs:8020///user/185"
  stackable:
    operators:
      - zookeeper
      - hdfs
      - commons
      - secret
      - listener
components:
  kafka: true
  hdfs: true
  alertSimulator: true
  minio: false
spec:
  destination:
    server: https://kubernetes.default.svc
  sparkNamespace: spark
  source:
    repoURL: https://github.com/astrolabsoftware/fink-cd
    targetRevision:
      default: nil
      # Revision for the fink-alert-simulator chart
      finkalertsimulator: nil
      # Revision for the fink-broker chart
      finkbroker: nil
