s3:
  enabled: false
  bucket: fink-broker-online
  endpoint: https://minio.minio:443
stackable:
  enabled: true
  operators:
    - zookeeper
    - hdfs
    - commons
    - secret
    - listener
e2e:
  # Install applications required by fink for end-to-end testing:
  # minio-operator, minio-tenant, fink-alert-simulator
  # strimzi, kafka-cluster
  enabled: true
spec:
  destination:
    server: https://kubernetes.default.svc
  sparkNamespace: spark
  source:
    repoURL: https://github.com/astrolabsoftware/fink-cd
    targetRevision:
      default: nil
      # Revision for the fink-alert-simulator chart
      finkalertsimulator: nil
      # Revision for the fink-broker chart
      finkbroker: nil
