apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: fink-producer
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: fink-prereq
    strimzi.io/cluster: "kafka-cluster"
spec:
  authentication:
    type: scram-sha-512