apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ztf-stream-sim
  labels:
    strimzi.io/cluster: "kafka-cluster"
spec:
  partitions: 3
  replicas: 1
  topicName: fink_sn_candidates_ztf
